// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ServeRoute.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Tp int32

const (
	Tp_Tp_UnKnown  Tp = 0
	Tp_Tp_NotStart Tp = 1
	Tp_Tp_Process  Tp = 2
	Tp_Tp_End      Tp = 3
)

var Tp_name = map[int32]string{
	0: "Tp_UnKnown",
	1: "Tp_NotStart",
	2: "Tp_Process",
	3: "Tp_End",
}

var Tp_value = map[string]int32{
	"Tp_UnKnown":  0,
	"Tp_NotStart": 1,
	"Tp_Process":  2,
	"Tp_End":      3,
}

func (x Tp) String() string {
	return proto.EnumName(Tp_name, int32(x))
}

func (Tp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_99e8d50a95d34bb2, []int{0}
}

//定义传输过程用到的数据类型,数字代表内部成员序号
type Name struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e8d50a95d34bb2, []int{0}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Id struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e8d50a95d34bb2, []int{1}
}

func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (m *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(m, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Time                 int64    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e8d50a95d34bb2, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type Activity struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tp                   Tp       `protobuf:"varint,2,opt,name=tp,proto3,enum=proto.Tp" json:"tp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Activity) Reset()         { *m = Activity{} }
func (m *Activity) String() string { return proto.CompactTextString(m) }
func (*Activity) ProtoMessage()    {}
func (*Activity) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e8d50a95d34bb2, []int{3}
}

func (m *Activity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Activity.Unmarshal(m, b)
}
func (m *Activity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Activity.Marshal(b, m, deterministic)
}
func (m *Activity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Activity.Merge(m, src)
}
func (m *Activity) XXX_Size() int {
	return xxx_messageInfo_Activity.Size(m)
}
func (m *Activity) XXX_DiscardUnknown() {
	xxx_messageInfo_Activity.DiscardUnknown(m)
}

var xxx_messageInfo_Activity proto.InternalMessageInfo

func (m *Activity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Activity) GetTp() Tp {
	if m != nil {
		return m.Tp
	}
	return Tp_Tp_UnKnown
}

func init() {
	proto.RegisterEnum("proto.Tp", Tp_name, Tp_value)
	proto.RegisterType((*Name)(nil), "proto.Name")
	proto.RegisterType((*Id)(nil), "proto.Id")
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*Activity)(nil), "proto.Activity")
}

func init() { proto.RegisterFile("ServeRoute.proto", fileDescriptor_99e8d50a95d34bb2) }

var fileDescriptor_99e8d50a95d34bb2 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4f, 0xf3, 0x30,
	0x10, 0xc5, 0x13, 0x37, 0xed, 0xf7, 0xf5, 0x22, 0xa5, 0x91, 0xc5, 0x50, 0x32, 0x55, 0x66, 0xa9,
	0x90, 0xc8, 0x50, 0x26, 0xc6, 0x0e, 0xa8, 0xaa, 0x90, 0x2a, 0x94, 0xba, 0x73, 0x08, 0xf5, 0x0d,
	0x1e, 0x62, 0x5b, 0xce, 0x51, 0xc4, 0x7f, 0x8f, 0x62, 0x12, 0x58, 0x3a, 0xf9, 0xf9, 0xf7, 0xfc,
	0xe4, 0x77, 0x07, 0xf9, 0x11, 0xfd, 0x05, 0x2b, 0xfb, 0x41, 0x58, 0x3a, 0x6f, 0xc9, 0xf2, 0x69,
	0x38, 0x44, 0x01, 0xc9, 0xa1, 0x69, 0x91, 0x73, 0x48, 0x4c, 0xd3, 0xe2, 0x32, 0x5e, 0xc5, 0xeb,
	0x79, 0x15, 0xb4, 0xb8, 0x01, 0xb6, 0x57, 0x3c, 0x03, 0xa6, 0x55, 0xe0, 0xd3, 0x8a, 0x69, 0x25,
	0x4a, 0x48, 0x4e, 0x1d, 0xfa, 0x6b, 0x89, 0x9e, 0x91, 0x6e, 0x71, 0xc9, 0x56, 0xf1, 0x7a, 0x52,
	0x05, 0x2d, 0x9e, 0xe0, 0xff, 0xf6, 0x4c, 0xfa, 0xa2, 0xe9, 0xeb, 0x6a, 0xe6, 0x16, 0x18, 0xb9,
	0x90, 0xc8, 0x36, 0xf3, 0x9f, 0x72, 0xa5, 0x74, 0x15, 0x23, 0x77, 0xbf, 0x05, 0x26, 0x1d, 0xcf,
	0x00, 0xa4, 0xab, 0x4f, 0xe6, 0xc5, 0xd8, 0x4f, 0x93, 0x47, 0x7c, 0x01, 0xa9, 0x74, 0xf5, 0xc1,
	0xd2, 0x91, 0x1a, 0x4f, 0x79, 0x3c, 0x3c, 0x78, 0xf5, 0xf6, 0x8c, 0x5d, 0x97, 0x33, 0x0e, 0x30,
	0x93, 0xae, 0x7e, 0x36, 0x2a, 0x9f, 0x6c, 0xde, 0x00, 0xfe, 0x46, 0xe7, 0x77, 0xf0, 0x6f, 0x87,
	0x14, 0xea, 0x8f, 0x5f, 0xed, 0x55, 0x91, 0x0e, 0xb2, 0xe7, 0x22, 0xe2, 0x0f, 0x90, 0xee, 0x90,
	0x7e, 0x3b, 0x8f, 0x6e, 0xbf, 0xa6, 0x62, 0x31, 0x5c, 0x46, 0x57, 0x44, 0xef, 0xb3, 0x40, 0x1e,
	0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xbb, 0x9c, 0xb0, 0x63, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServeRouteClient is the client API for ServeRoute service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServeRouteClient interface {
	GetUser(ctx context.Context, in *Id, opts ...grpc.CallOption) (*User, error)
	GetActivity(ctx context.Context, in *Name, opts ...grpc.CallOption) (*Activity, error)
}

type serveRouteClient struct {
	cc *grpc.ClientConn
}

func NewServeRouteClient(cc *grpc.ClientConn) ServeRouteClient {
	return &serveRouteClient{cc}
}

func (c *serveRouteClient) GetUser(ctx context.Context, in *Id, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/proto.ServeRoute/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serveRouteClient) GetActivity(ctx context.Context, in *Name, opts ...grpc.CallOption) (*Activity, error) {
	out := new(Activity)
	err := c.cc.Invoke(ctx, "/proto.ServeRoute/GetActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServeRouteServer is the server API for ServeRoute service.
type ServeRouteServer interface {
	GetUser(context.Context, *Id) (*User, error)
	GetActivity(context.Context, *Name) (*Activity, error)
}

// UnimplementedServeRouteServer can be embedded to have forward compatible implementations.
type UnimplementedServeRouteServer struct {
}

func (*UnimplementedServeRouteServer) GetUser(ctx context.Context, req *Id) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedServeRouteServer) GetActivity(ctx context.Context, req *Name) (*Activity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivity not implemented")
}

func RegisterServeRouteServer(s *grpc.Server, srv ServeRouteServer) {
	s.RegisterService(&_ServeRoute_serviceDesc, srv)
}

func _ServeRoute_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServeRouteServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ServeRoute/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServeRouteServer).GetUser(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServeRoute_GetActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServeRouteServer).GetActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ServeRoute/GetActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServeRouteServer).GetActivity(ctx, req.(*Name))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServeRoute_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ServeRoute",
	HandlerType: (*ServeRouteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _ServeRoute_GetUser_Handler,
		},
		{
			MethodName: "GetActivity",
			Handler:    _ServeRoute_GetActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ServeRoute.proto",
}
