// Code generated by protoc-gen-go. DO NOT EDIT.
// source: query.proto

package query

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Tp int32

const (
	//未知
	Tp_Tp_UnKnown Tp = 0
	//未开始
	Tp_Tp_NotStart Tp = 1
	//进行中
	Tp_Tp_Process Tp = 2
	//结束了
	Tp_Tp_End Tp = 3
)

var Tp_name = map[int32]string{
	0: "Tp_UnKnown",
	1: "Tp_NotStart",
	2: "Tp_Process",
	3: "Tp_End",
}

var Tp_value = map[string]int32{
	"Tp_UnKnown":  0,
	"Tp_NotStart": 1,
	"Tp_Process":  2,
	"Tp_End":      3,
}

func (x Tp) String() string {
	return proto.EnumName(Tp_name, int32(x))
}

func (Tp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{0}
}

//定义传输过程用到的数据类型,数字代表内部成员序号
type Name struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{0}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserId struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{1}
}

func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (m *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(m, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Time                 int64    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type Activity struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tp                   Tp       `protobuf:"varint,2,opt,name=tp,proto3,enum=query.Tp" json:"tp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Activity) Reset()         { *m = Activity{} }
func (m *Activity) String() string { return proto.CompactTextString(m) }
func (*Activity) ProtoMessage()    {}
func (*Activity) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{3}
}

func (m *Activity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Activity.Unmarshal(m, b)
}
func (m *Activity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Activity.Marshal(b, m, deterministic)
}
func (m *Activity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Activity.Merge(m, src)
}
func (m *Activity) XXX_Size() int {
	return xxx_messageInfo_Activity.Size(m)
}
func (m *Activity) XXX_DiscardUnknown() {
	xxx_messageInfo_Activity.DiscardUnknown(m)
}

var xxx_messageInfo_Activity proto.InternalMessageInfo

func (m *Activity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Activity) GetTp() Tp {
	if m != nil {
		return m.Tp
	}
	return Tp_Tp_UnKnown
}

func init() {
	proto.RegisterEnum("query.Tp", Tp_name, Tp_value)
	proto.RegisterType((*Name)(nil), "query.Name")
	proto.RegisterType((*UserId)(nil), "query.UserId")
	proto.RegisterType((*User)(nil), "query.User")
	proto.RegisterType((*Activity)(nil), "query.Activity")
}

func init() { proto.RegisterFile("query.proto", fileDescriptor_5c6ac9b241082464) }

var fileDescriptor_5c6ac9b241082464 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4f, 0xf3, 0x30,
	0x10, 0xc5, 0x13, 0x37, 0xc9, 0xf7, 0xf5, 0x22, 0xd2, 0xe8, 0xa6, 0x90, 0xa9, 0xf2, 0x42, 0x85,
	0x44, 0x86, 0x32, 0x31, 0x76, 0x40, 0x15, 0x42, 0xaa, 0x20, 0xb8, 0x73, 0x14, 0x1a, 0x0f, 0x1e,
	0x62, 0x1b, 0xe7, 0x00, 0xf5, 0xbf, 0x47, 0x71, 0x53, 0xc4, 0xd0, 0xed, 0x9e, 0x7f, 0x7e, 0xf6,
	0xbb, 0x07, 0xe9, 0xc7, 0xa7, 0x74, 0xc7, 0xca, 0x3a, 0x43, 0x06, 0x63, 0x2f, 0x78, 0x09, 0xd1,
	0xae, 0xed, 0x25, 0x22, 0x44, 0xba, 0xed, 0x65, 0x11, 0x2e, 0xc3, 0xd5, 0xbc, 0xf6, 0x33, 0x2f,
	0x20, 0xd9, 0x0f, 0xd2, 0x3d, 0x75, 0x98, 0x01, 0x53, 0x9d, 0x67, 0x71, 0xcd, 0x54, 0xc7, 0x2b,
	0x88, 0x46, 0x72, 0xc9, 0x35, 0x9e, 0x91, 0xea, 0x65, 0xc1, 0x96, 0xe1, 0x6a, 0x56, 0xfb, 0x99,
	0x3f, 0xc0, 0xff, 0xcd, 0x81, 0xd4, 0x97, 0xa2, 0xe3, 0x45, 0xcf, 0x35, 0x30, 0xb2, 0xde, 0x91,
	0xad, 0xe7, 0xd5, 0x29, 0xa6, 0xb0, 0x35, 0x23, 0x7b, 0xbb, 0x01, 0x26, 0x2c, 0x66, 0x00, 0xc2,
	0x36, 0x7b, 0xfd, 0xac, 0xcd, 0xb7, 0xce, 0x03, 0x5c, 0x40, 0x2a, 0x6c, 0xb3, 0x33, 0xf4, 0x46,
	0xad, 0xa3, 0x3c, 0x9c, 0x2e, 0xbc, 0x38, 0x73, 0x90, 0xc3, 0x90, 0x33, 0x04, 0x48, 0x84, 0x6d,
	0x1e, 0x75, 0x97, 0xcf, 0xd6, 0x0d, 0xc4, 0xaf, 0xe3, 0x93, 0x78, 0x03, 0xff, 0xb6, 0x92, 0x7c,
	0xf2, 0xab, 0xe9, 0x97, 0xd3, 0x82, 0x65, 0xfa, 0x47, 0xf2, 0x00, 0xef, 0x20, 0xdd, 0x4a, 0xfa,
	0x8d, 0x7c, 0xa6, 0x63, 0x53, 0xe5, 0x62, 0x12, 0x67, 0xca, 0x83, 0xf7, 0xc4, 0x57, 0x7a, 0xff,
	0x13, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xdb, 0x1a, 0x4b, 0x61, 0x01, 0x00, 0x00,
}
