// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: query.proto

package query

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Query service

type QueryService interface {
	GetUser(ctx context.Context, in *UserId, opts ...client.CallOption) (*User, error)
	GetActivity(ctx context.Context, in *Name, opts ...client.CallOption) (*Activity, error)
}

type queryService struct {
	c    client.Client
	name string
}

func NewQueryService(name string, c client.Client) QueryService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "query"
	}
	return &queryService{
		c:    c,
		name: name,
	}
}

func (c *queryService) GetUser(ctx context.Context, in *UserId, opts ...client.CallOption) (*User, error) {
	req := c.c.NewRequest(c.name, "Query.GetUser", in)
	out := new(User)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryService) GetActivity(ctx context.Context, in *Name, opts ...client.CallOption) (*Activity, error) {
	req := c.c.NewRequest(c.name, "Query.GetActivity", in)
	out := new(Activity)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Query service

type QueryHandler interface {
	GetUser(context.Context, *UserId, *User) error
	GetActivity(context.Context, *Name, *Activity) error
}

func RegisterQueryHandler(s server.Server, hdlr QueryHandler, opts ...server.HandlerOption) error {
	type query interface {
		GetUser(ctx context.Context, in *UserId, out *User) error
		GetActivity(ctx context.Context, in *Name, out *Activity) error
	}
	type Query struct {
		query
	}
	h := &queryHandler{hdlr}
	return s.Handle(s.NewHandler(&Query{h}, opts...))
}

type queryHandler struct {
	QueryHandler
}

func (h *queryHandler) GetUser(ctx context.Context, in *UserId, out *User) error {
	return h.QueryHandler.GetUser(ctx, in, out)
}

func (h *queryHandler) GetActivity(ctx context.Context, in *Name, out *Activity) error {
	return h.QueryHandler.GetActivity(ctx, in, out)
}
