// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package pkg

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitWeb() (*WebHandler, error) {
	config := DefaultConfig()
	userServiceClient := DefaultUserService(config)
	db := NewDatabase(config)
	webHandler := &WebHandler{
		Config:      config,
		UserService: userServiceClient,
		DB:          db,
	}
	return webHandler, nil
}

func InitUserService() (*UserServiceHandler, error) {
	config := DefaultConfig()
	db := NewDatabase(config)
	userServiceHandler := &UserServiceHandler{
		Config: config,
		DB:     db,
	}
	return userServiceHandler, nil
}

// wire.go:

var configSet = wire.NewSet(DefaultConfig)
